### ISSUE TITLE
It does not work with minecraft 1.11 or 1.11.2

### ISSUE THREAD

**Issue by ghost** [ArtixAllMighty/PSG-Revamped#1]
Here is the crash file. This is from a comment on... https://minecraft.curseforge.com/projects/painting-selection-gui-revamped?comment=4

[fml-client-latest.zip](https://github.com/ArtixAllMighty/PSG-Revamped/files/699151/fml-client-latest.zip)

**Comment by AbsolemJackdaw** [comment]
1.11 got launched. 1.10.2 wasn't compatible with the update. issue closed
