### ISSUE TITLE
request

### ISSUE THREAD

**Issue by EmanYm** [ArtixAllMighty/PSG-Revamped#2]
Is there any chance you can make this work so it is not required to be on a client if it is on a server?

**Comment by AbsolemJackdaw** [comment]
rendering is done client side. i can't render stuff on the client's screen if it's server side only.

**Comment by EmanYm** [comment]
What I meant is it would only need to render the gui if the client had this installed.
My player base doesn't need to have this, as it's an adventure style server and they won't be placing paintings.  I'd like to only have my staff use this.

**Comment by AbsolemJackdaw** [comment]
does the client crash of the server has PSG installed but not the client ?

**Comment by EmanYm** [comment]
The client is refused connection with the missing mod message.

**Comment by EmanYm** [comment]
Have you given this any more thought?
