### ISSUE TITLE
Painting GUI not invoking on placements of painting

### ISSUE THREAD

**Issue by MxtressMyxx** [ArtixAllMighty/PSG-Revamped#4]
As title implies, the painting selector GUI does not appear when a painting is placed.

When trying to use the command, the only output is:
"rror - No painting selected" (yes, the 'E' is truncated in chat output)

No error is produced in server log.

**Comment by Apollyna** [comment]
Can confirm, also not working for me. Would be happy to post any logs necessary. I don't know how to mod but if there's a "simple switch" to flip to get this working, I'd love to know to try and attempt it myself , too!

**Comment by AbsolemJackdaw** [comment]
So i took the time to test the mod in dev environement and it seems to work. 
what version are you on ? what else are you using ? what are you doing to try and invoke the placement gui ?

**Comment by AbsolemJackdaw** [comment]
Tested latest version in modded forge as well, sole mod. it works.

if you are using both the psg and paintings++, they currently dont work together anymore.
Im going to merge both soon

**Comment by Apollyna** [comment]
Hello! Thanks for wanting to work through this!

While I can't speak for the other commenters, I'm personally using the following:
forge1.12.2-14.23.3.2655
morepaintings-paintings-1.12.2-4.0.0.1
paintingselgui-PSG+Revamed-1.12.2-1.1.0.1

I start up my game and attempt to place a painting by right clicking on a wall with the item held in hand, as normal - A Paintings++ painting shows up just fine (i'm using the extended version) but at no time does a GUI pop up, so the placement is random and i have to destroy and replace to get the exact picture I want. If I try to use the /paintings command (my memory is fuzzy, but another commenter tried this so I did too) I also get the "rror, no painting selected" (sic) message.

EDIT:: I see you say Paintings++ and PSG no longer work together, that would be exactly the problem. I'm guessing when you say merge that means a fix will come out? Best of luck on it, I'll be very excited to see! Thank you for keeping up to date with this!

**Comment by finley243** [comment]
A temporary fix is just rolling back to version 3.3.0.0 of Paintings++ until the merge is released. Worked just fine for me.
